### DISCUSSION TITLE
homeassistant

### DISCUSSION THREAD

**Discussion by vpritulin** [txubelaxu/esphome-jk-bms#16] [Q&A]
Hello! I have a JK-PB1A16S-15P bms and I want to connect it to an esp8266 nodemcu v3 using a TTL to RS-485 module. I have 1 akb and 1 bms, that is, there is no master and slave.
But when compiling I get an error. 

Could you tell me what I'm doing wrong?

![image](https://github.com/user-attachments/assets/dace9a3f-526d-4531-974e-ad35a170573c)

My yaml file

```
substitutions:
  esp_name: esp-rs485-gw
  bms0_name: rs485-bms0
  device_description: "Monitor two JK-BMS via RS485 internal"
  external_components_source: github://txubelaxu/esphome-jk-bms@main #github://syssi/esphome-jk-bms@main
  tx_pin_uart_0: GPIO1 #GPIO16
  rx_pin_uart_0: GPIO3 #GPIO17
  talk_pin_rs485: GPIO4

esphome:
  name: ${esp_name}
  comment: ${device_description}

esp8266:
  board: esp01_1m

external_components:
 - source: ${external_components_source}
   refresh: 0s
#  - source: ./components
#    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO #VERY_VERBOSE #VERBOSE #DEBUG #INFO #DEBUG
  tx_buffer_size: 1024

api:
  encryption:
    key: "1234"

ota:
  - platform: esphome
    password: "1234"

web_server:
  local: true
  port: 80

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 1000
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: "JK02_32S"
    rx_timeout: 500ms
    uart_id: uart_0
    talk_pin: ${talk_pin_rs485}

jk_rs485_bms:
  - id: bms0
    rs485_address: 0x00
    update_interval: 5s

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    status_balancing:
      name: "${bms0_name} status balancing"
    status_precharging:
      name: "${bms0_name} status precharging"      
    status_charging:
      name: "${bms0_name} status charging"
    status_discharging:
      name: "${bms0_name} status discharging"
    status_online:
      name: "${bms0_name} status online"
    status_heating:
      name: "${bms0_name} status heating"      
    alarm_wireres:
      name: "${bms0_name} alarm WireRes"
    alarm_mosotp:
      name: "${bms0_name} alarm MosOTP"
    alarm_cellquantity:
      name: "${bms0_name} alarm CellQuantity"
    alarm_cursensorerr:
      name: "${bms0_name} alarm CurSensorErr"
    alarm_cellovp:
      name: "${bms0_name} alarm CellOVP"
    alarm_batovp:
      name: "${bms0_name} alarm BatOVP"
    alarm_chocp:
      name: "${bms0_name} alarm ChOCP"
    alarm_chscp:
      name: "${bms0_name} alarm ChSCP"
    alarm_chotp:
      name: "${bms0_name} alarm ChOTP"
    alarm_chutp:
      name: "${bms0_name} alarm ChUTP"
    alarm_cpuauxcommuerr:
      name: "${bms0_name} alarm CPUAuxCommuErr"
    alarm_celluvp:
      name: "${bms0_name} alarm CellUVP"
    alarm_batuvp:
      name: "${bms0_name} alarm BatUVP"
    alarm_dchocp:
      name: "${bms0_name} alarm DchOCP"
    alarm_dchscp:
      name: "${bms0_name} alarm DchSCP"
    alarm_dchotp:
      name: "${bms0_name} alarm DchOTP"
    alarm_chargemos:
      name: "${bms0_name} alarm ChargeMOS"
    alarm_dischargemos:
      name: "${bms0_name} alarm DischargeMOS"
    alarm_gpsdisconneted:
      name: "${bms0_name} alarm GPSDisconneted"
    alarm_modifypwdintime:
      name: "${bms0_name} alarm ModifyPWDinTime"
    alarm_dischargeonfailed:
      name: "${bms0_name} alarm DischargeOnFailed"
    alarm_batteryovertemp:
      name: "${bms0_name} alarm BatteryOverTemp"
    alarm_temperaturesensoranomaly:
      name: "${bms0_name} alarm TemperatureSensorAnomaly"
    alarm_plcmoduleanomaly:
      name: "${bms0_name} alarm PLCModuleAnomaly"
    alarm_mostempsensorabsent:
      name: "${bms0_name} alarm MOSTempSensorAbsent"
    alarm_battempsensor1absent:
      name: "${bms0_name} alarm BATTempSensor1Absent"
    alarm_battempsensor2absent:
      name: "${bms0_name} alarm BATTempSensor2Absent"
    alarm_battempsensor3absent:
      name: "${bms0_name} alarm BATTempSensor3Absent"
    alarm_battempsensor4absent:
      name: "${bms0_name} alarm BATTempSensor4Absent"
    alarm_battempsensor5absent:
      name: "${bms0_name} alarm BATTempSensor5Absent"


sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing_direction:
      name: "${bms0_name} balancing direction"
    cell_smart_sleep_voltage:
      name: "${bms0_name} cell smart sleep voltage"
    cell_voltage_min:
      name: "${bms0_name} cell voltage min"
    cell_voltage_max:
      name: "${bms0_name} cell voltage max"
    cell_voltage_min_cell_number:
      name: "${bms0_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      name: "${bms0_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${bms0_name} cell delta voltage"
    cell_average_voltage:
      name: "${bms0_name} cell average voltage"
    cell_resistance_min:
      name: "${bms0_name} cell resistance min"
    cell_resistance_max:
      name: "${bms0_name} cell resistance max"      
    cell_resistance_min_cell_number:
      name: "${bms0_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${bms0_name} cell resistance max cell number"      
    cell_voltage_01:
      name: "${bms0_name} cell voltage 01"
    cell_voltage_02:
      name: "${bms0_name} cell voltage 02"
    cell_voltage_03:
      name: "${bms0_name} cell voltage 03"
    cell_voltage_04:
      name: "${bms0_name} cell voltage 04"
    cell_voltage_05:
      name: "${bms0_name} cell voltage 05"
    cell_voltage_06:
      name: "${bms0_name} cell voltage 06"
    cell_voltage_07:
      name: "${bms0_name} cell voltage 07"
    cell_voltage_08:
      name: "${bms0_name} cell voltage 08"
    cell_voltage_09:
      name: "${bms0_name} cell voltage 09"
    cell_voltage_10:
      name: "${bms0_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms0_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms0_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms0_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms0_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms0_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms0_name} cell voltage 16"
    cell_voltage_17:
      name: "${bms0_name} cell voltage 17"
    cell_voltage_18:
      name: "${bms0_name} cell voltage 18"
    cell_voltage_19:
      name: "${bms0_name} cell voltage 19"
    cell_voltage_20:
      name: "${bms0_name} cell voltage 20"
    cell_voltage_21:
      name: "${bms0_name} cell voltage 21"
    cell_voltage_22:
      name: "${bms0_name} cell voltage 22"
    cell_voltage_23:
      name: "${bms0_name} cell voltage 23"
    cell_voltage_24:
      name: "${bms0_name} cell voltage 24"
    cell_resistance_01:
      name: "${bms0_name} cell resistance 01"
    cell_resistance_02:
      name: "${bms0_name} cell resistance 02"
    cell_resistance_03:
      name: "${bms0_name} cell resistance 03"
    cell_resistance_04:
      name: "${bms0_name} cell resistance 04"
    cell_resistance_05:
      name: "${bms0_name} cell resistance 05"
    cell_resistance_06:
      name: "${bms0_name} cell resistance 06"
    cell_resistance_07:
      name: "${bms0_name} cell resistance 07"
    cell_resistance_08:
      name: "${bms0_name} cell resistance 08"
    cell_resistance_09:
      name: "${bms0_name} cell resistance 09"
    cell_resistance_10:
      name: "${bms0_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms0_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms0_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms0_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms0_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms0_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms0_name} cell resistance 16"
    cell_resistance_17:
      name: "${bms0_name} cell resistance 17"
    cell_resistance_18:
      name: "${bms0_name} cell resistance 18"
    cell_resistance_19:
      name: "${bms0_name} cell resistance 19"
    cell_resistance_20:
      name: "${bms0_name} cell resistance 20"
    cell_resistance_21:
      name: "${bms0_name} cell resistance 21"
    cell_resistance_22:
      name: "${bms0_name} cell resistance 22"
    cell_resistance_23:
      name: "${bms0_name} cell resistance 23"
    cell_resistance_24:
      name: "${bms0_name} cell resistance 24"
    battery_voltage:
      name: "${bms0_name} battery voltage"
    battery_current:
      name: "${bms0_name} battery current"
    battery_power:
      name: "${bms0_name} battery power"
    battery_power_charging:
      name: "${bms0_name} battery power charging"
    battery_power_discharging:
      name: "${bms0_name} battery power discharging"
    temperature_sensor_1:
      name: "${bms0_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms0_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms0_name} temperature sensor 4"
    temperature_sensor_5:
      name: "${bms0_name} temperature sensor 5"
    temperature_powertube:
      name: "${bms0_name} temperature powertube"
    battery_capacity_state_of_charge:
      name: "${bms0_name} battery capacity state of charge"
    battery_capacity_remaining:
      name: "${bms0_name} battery capacity remaining"
    battery_capacity_total_setting:
      name: "${bms0_name} battery capacity total setting"
    charging_cycles:
      name: "${bms0_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${bms0_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${bms0_name} battery total runtime"
    balancing_current:
      name: "${bms0_name} balancing current"
    errors_bitmask:
      name: "${bms0_name} errors bitmask"
    cell_count_settings:
      name: "${bms0_name} cell count settings"
    cell_count_real:
      name: "${bms0_name} cell count real"      
    cell_overvoltage_protection:
      name: "${bms0_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms0_name} cell overvoltage protection recovery"
    cell_request_charge_voltage:
      name: "${bms0_name} cell request charge voltage"      
    cell_request_charge_voltage_time:
      name: "${bms0_name} cell request charge voltage time"    
    cell_request_float_voltage:
      name: "${bms0_name} cell request float voltage"   
    cell_request_float_voltage_time:
      name: "${bms0_name} cell request float voltage time"        
    balancing_trigger_voltage:
      name: "${bms0_name} balancing trigger voltage"         
    cell_balancing_starting_voltage:
      name: "${bms0_name} cell balancing starting voltage"  
    max_balancing_current:
      name: "${bms0_name} max balancing current"          
    cell_soc100_voltage:
      name: "${bms0_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms0_name} cell soc0 voltage"  
    cell_undervoltage_protection:
      name: "${bms0_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms0_name} cell undervoltage protection recovery"                     
    cell_power_off_voltage:
      name: "${bms0_name} cell power off voltage"      
    smart_sleep_time:
      name: "${bms0_name} smart sleep time"
    max_charging_current:
      name: "${bms0_name} max charging current"      
    max_discharging_current:
      name: "${bms0_name} max discharging current"   
    charging_overcurrent_protection_delay:
      name: "${bms0_name} charging overcurrent protection delay"
    charging_overcurrent_protection_recovery_delay:
      name: "${bms0_name} charging overcurrent protection recovery delay"
    discharging_overcurrent_protection_delay:
      name: "${bms0_name} discharging overcurrent protection delay"
    discharging_overcurrent_protection_recovery_delay:
      name: "${bms0_name} discharging overcurrent protection recovery delay"   
    short_circuit_protection_delay:
      name: "${bms0_name} short circuit protection delay"  
    short_circuit_protection_recovery_delay:
      name: "${bms0_name} short circuit protection recovery delay"                     
    precharging_time_from_discharge:
      name: "${bms0_name} precharging time from discharge"       
    charging_overtemperature_protection:
      name: "${bms0_name} charging overtemperature protection"
    charging_overtemperature_protection_recovery:
      name: "${bms0_name} charging overtemperature protection recovery"
    discharging_overtemperature_protection:
      name: "${bms0_name} discharging overtemperature protection"
    discharging_overtemperature_protection_recovery:
      name: "${bms0_name} discharging overtemperature protection recovery" 
    charging_lowtemperature_protection:
      name: "${bms0_name} charging lowtemperature protection"
    charging_lowtemperature_protection_recovery:
      name: "${bms0_name} charging lowtemperature protection recovery"
    mos_overtemperature_protection:
      name: "${bms0_name} mos overtemperature protection"
    mos_overtemperature_protection_recovery:
      name: "${bms0_name} mos overtemperature protection recovery"   
    powertube_temperature_protection:
      name: "${bms0_name} powertube temperature protection" 
    powertube_temperature_protection_recovery:
      name: "${bms0_name} powertube temperature protection recovery"  
    battery_total_alarms_count:     
      name: "${bms0_name} battery total alarms count"  
    battery_total_alarms_active:     
      name: "${bms0_name} battery total alarms active"  
    emergency_time_countdown:
      name: "${bms0_name} emergency time countdown"      
    uart1_protocol_number:
      name: "${bms0_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${bms0_name} uart2 protocol number"  
    battery_soh_valuation:    
      name: "${bms0_name} battery soh valuation"
    discharging_overcurrent_protection_release_time:    
      name: "${bms0_name} discharging overcurrent protection release time"
    discharging_short_circuit_protection_release_time:    
      name: "${bms0_name} discharging short circuit protection release time"
    charging_overcurrent_protection_release_time:    
      name: "${bms0_name} charging overcurrent protection release time"
    charging_short_circuit_protection_release_time:    
      name: "${bms0_name} charging short circuit protection release time"
    cell_undervoltage_protection_release_time:    
      name: "${bms0_name} cell undervoltage protection release time"
    cell_overvoltage_protection_release_time:    
      name: "${bms0_name} cell overvoltage protection release time"

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    precharging:
      name: "${bms0_name} precharging"
    charging:
      name: "${bms0_name} charging"
    discharging:
      name: "${bms0_name} discharging"
    balancing:
      name: "${bms0_name} balancing"
    emergency:
      name: "${bms0_name} emergency"
    heating:
      name: "${bms0_name} heating"
    display_always_on:
      name: "${bms0_name} display_always_on"
    charging_float_mode:
      name: "${bms0_name} charging float mode"
    timed_stored_data:
      name: "${bms0_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms0_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms0_name} smart sleep on"
    disable_pcl_module:
      name: "${bms0_name} disable pcl module"
    gps_heartbeat:
      name: "${bms0_name} gps heartbeat"
    port_selection:
      name: "${bms0_name} port selection"
    special_charger:
      name: "${bms0_name} special charger"            

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    errors:
      name: "${bms0_name} errors"
    operation_status:
      name: "${bms0_name} operation status"
    battery_type:
      name: "${bms0_name} battery type"

    total_runtime_formatted:
      name: "${bms0_name} total runtime formatted"
    info_vendorid:
      name: "${bms0_name} info vendorid"
    info_hardware_version:
      name: "${bms0_name} info hardware version"
    info_software_version:
      name: "${bms0_name} info software version"
    info_device_name:
      name: "${bms0_name} info device name"
    info_device_password:
      name: "${bms0_name} info device password"   
    network_nodes_available:
      name: "${bms0_name} network nodes available"  
    info_device_serial_number:
      name: "${bms0_name} info device serial number"  

```
