### DISCUSSION TITLE
ESP32 POE Version

### DISCUSSION THREAD

**Discussion by Imanol82** [txubelaxu/esphome-jk-bms#26] [Q&A]
Hello!

I'm trying to make this proyecto on an ESP32 C3 POE with RS485 isolated board:

![image](https://github.com/user-attachments/assets/3518c6e5-8932-4893-91cc-c833f7463621)

I would like to use 1 Master and 1 Slave, I know in this way I could't write but is OK, in this project I only need to read.

So, I have added neccesary external components to the yaml to use this ESP32 but something is wrong:

```
I have delete this code because the new post is more clear.

https://github.com/txubelaxu/esphome-jk-bms/discussions/26#discussioncomment-11296283
```

Thank you very much for your help!!

**Comment by Imanol82** [comment]
In the end I've installed Sleeper85 project and works perfectly in this POE esp32.

Thank you very much!

**Comment by Imanol82** [comment]
Hello, I'm back.

I've been using Sleeper85 (and yours) YamBMS for a few weeks and it works well with the ESP32 POE (many thanks to @Sleeper85 for all your help), but I still like the idea of ​​using the ESP32 only for reading the system, not like the Master. That is, let my both JK-PB (master + slave) connect via CAN to my Deye inverter.

I think it is the most correct way of working.

So I'm trying again to install your project to the ESP32 ETH01-evo POE.

The scheme is very similar to the one I used with the YamBMS, because the RS485 side is yours. So I thought it would be very easy to port it.

![image](https://github.com/user-attachments/assets/f239daf7-1aef-4b40-bfbc-52953c699d46)

After changing the pins, adding the repository where the Ethernet component is and adding it, I left the code like this:

```
substitutions:
  esp_name: esp-rs485-gw
  bms0_name: bms1
  bms1_name: bms2
  device_description: "Monitor two JK-BMS via RS485 internal"
  external_components_source: github://txubelaxu/esphome-jk-bms@main #github://syssi/esphome-jk-bms@main
  tx_pin_uart_0: GPIO2 #GPIO1 #GPIO16
  rx_pin_uart_0: GPIO5 #GPIO3 #GPIO17
  talk_pin_rs485: GPIO4

esphome:
  name: ${esp_name}
  comment: ${device_description}
  project:
    name: "txubelaxu.esphome-jk-bms"
    version: 2.0.1
#  libraries:
#    - "ArduinoJson"
#  includes:
    #- ./components/ArduinoJson/ArduinoJson.h
    #- ./components/ArduinoJson/ArduinoJson.hpp
    #- ./components/ArduinoJson/Configuration.hpp
#    - ./components/json/json_util.h

#esp32:
#  board: esp32dev #nodemcu-32s #wemos_d1_mini32
#  framework:
#    type: esp-idf

#esp8266:
#  board: d1_mini

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.5.0

external_components:
# - source: ${external_components_source}
#   refresh: 0s
  #- source:
  #    type: git
  #    url: https://github.com/esphome/esphome
  #    ref: dev
  #  components: [ json ]

  - source: ./components
    refresh: 0s
    components: [ jk_rs485_sniffer , jk_rs485_bms ]
  - source: 
      type: git
      url: https://github.com/esphome/esphome
      ref: d5bdf2575c151abfad39b6c24c3856395a7d0901
    components:
      - ethernet

ethernet:
  id: my_network
  type: DM9051 # W5500
  clk_pin: 7
  mosi_pin: 10
  miso_pin: 3
  cs_pin: 9
  interrupt_pin: 8
  reset_pin: 6
  clock_speed: 20MHz
  manual_ip:
    static_ip: 192.168.178.114 
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1

ota:
  - platform: esphome
 
...
```

But it keeps giving me the same error... And I don't know how to continue.

![image](https://github.com/user-attachments/assets/cee45102-a561-44a3-8b09-adad8869d760)

@txubelaxu , could you help me to continue? I have always thought that this ESP32 POE is very interesting for this kind of proyects. It is wonderful to have to connect it only with a POE network cable, no wifi, no psu...

You can use me as a tester :)

Thank you very much for your work. It's a pleasure to find such interesting projects.



Mila esker, benetan zure laguntza asko eskertuko nukeela.
