### ISSUE TITLE
Slave only reporting at ESP32 restart

### ISSUE THREAD

**Issue by davidgp1701** [txubelaxu/esphome-jk-bms#47]
Hello,

I had this running with just 1 JK PB HW version 15 without problem. This JK BMS is configured as master and connected via CAN to a Victron Cerbo GX.

Yesterday I added a second battery, it is connected as a slave in address 0x01, and the ESP32 is connected to its second RS485 port. I can still get all values from the master battery, but the slave only sends data when the ESP32 restarts.

The only thing strange that I can find in the logs is this:

```
[11:58:27][D][jk_rs485_bms:594]: This BMS address is: 1  and address received 0 ==> IDLE
[11:58:27][W][component:237]: Component jk_rs485_sniffer took a long time for an operation (884 ms).
[11:58:27][W][component:238]: Components should block for at most 30 ms.
[11:58:27][D][jk_rs485_sniffer:522]: ..........................................
```

I have attached the full log, in case it is of help.

Both JK BMS are in version 15.38. My configuration is the following one:

```yaml
substitutions:
  esp_name: jk-monitor
  bms0_name: gobel01
  bms1_name: yixiang01
  device_description: "Monitor my JK-BMS via RS485 internal"
  external_components_source: github://txubelaxu/esphome-jk-bms@main #github://syssi/esphome-jk-bms@main
  tx_pin_uart_0: GPIO17 #GPIO1 #GPIO16
  rx_pin_uart_0: GPIO16 #GPIO3 #GPIO17
  talk_pin_rs485: GPIO4

esphome:
  name: ${esp_name}
  comment: ${device_description}
  project:
    name: "txubelaxu.esphome-jk-bms"
    version: "main"

#    version: 2.0.1
#  libraries:
#    - "ArduinoJson"
#  includes:
    #- ./components/ArduinoJson/ArduinoJson.h
    #- ./components/ArduinoJson/ArduinoJson.hpp
    #- ./components/ArduinoJson/Configuration.hpp
#    - ./components/json/json_util.h

esp32:
  board: esp32dev #nodemcu-32s #wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
# - source: ${external_components_source}
#   refresh: 0s
  #- source:
  #    type: git
  #    url: https://github.com/esphome/esphome
  #    ref: dev
  #  components: [ json ]

  - source: ${external_components_source}
    refresh: 0s
    components: [ jk_rs485_sniffer , jk_rs485_bms ]


mdns:
  disabled: true

ota:
  - platform: esphome
    password: "XXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.45.10

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jkmonitor Fallback Hotspot"
    password: "XXXXXX"


api:
  encryption:
    key: "XXXXXXXXXXXXXXXX"

logger:
  level: DEBUG #VERBOSE #DEBUG #INFO #VERY_VERBOSE #VERBOSE #DEBUG #INFO #DEBUG
  tx_buffer_size: 2048

#web_server:
#  local: true
#  port: 80
#  auth:
#     username: !secret web_server_user
#     password: !secret web_server_password

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 500
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: "JK02_32S"
    rx_timeout: 500ms
    uart_id: uart_0
    talk_pin: ${talk_pin_rs485}

jk_rs485_bms:
  - id: bms0
    rs485_address: 0x00
    jk_rs485_sniffer_id: sniffer0
    update_interval: 180s
  - id: bms1
    rs485_address: 0x01
    jk_rs485_sniffer_id: sniffer0
    update_interval: 180s

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    status_balancing:
      name: "${bms0_name} status balancing"
    status_precharging:
      name: "${bms0_name} status precharging"      
    status_charging:
      name: "${bms0_name} status charging"
    status_discharging:
      name: "${bms0_name} status discharging"
    status_online:
      name: "${bms0_name} status online"
    status_heating:
      name: "${bms0_name} status heating"      
    alarm_wireres:
      name: "${bms0_name} alarm WireRes"
    alarm_mosotp:
      name: "${bms0_name} alarm MosOTP"
    alarm_cellquantity:
      name: "${bms0_name} alarm CellQuantity"
    alarm_cursensorerr:
      name: "${bms0_name} alarm CurSensorErr"
    alarm_cellovp:
      name: "${bms0_name} alarm CellOVP"
    alarm_batovp:
      name: "${bms0_name} alarm BatOVP"
    alarm_chocp:
      name: "${bms0_name} alarm ChOCP"
    alarm_chscp:
      name: "${bms0_name} alarm ChSCP"
    alarm_chotp:
      name: "${bms0_name} alarm ChOTP"
    alarm_chutp:
      name: "${bms0_name} alarm ChUTP"
    alarm_cpuauxcommuerr:
      name: "${bms0_name} alarm CPUAuxCommuErr"
    alarm_celluvp:
      name: "${bms0_name} alarm CellUVP"
    alarm_batuvp:
      name: "${bms0_name} alarm BatUVP"
    alarm_dchocp:
      name: "${bms0_name} alarm DchOCP"
    alarm_dchscp:
      name: "${bms0_name} alarm DchSCP"
    alarm_dchotp:
      name: "${bms0_name} alarm DchOTP"
    alarm_chargemos:
      name: "${bms0_name} alarm ChargeMOS"
    alarm_dischargemos:
      name: "${bms0_name} alarm DischargeMOS"
    alarm_gpsdisconneted:
      name: "${bms0_name} alarm GPSDisconneted"
    alarm_modifypwdintime:
      name: "${bms0_name} alarm ModifyPWDinTime"
    alarm_dischargeonfailed:
      name: "${bms0_name} alarm DischargeOnFailed"
    alarm_batteryovertemp:
      name: "${bms0_name} alarm BatteryOverTemp"
    alarm_temperaturesensoranomaly:
      name: "${bms0_name} alarm TemperatureSensorAnomaly"
    alarm_plcmoduleanomaly:
      name: "${bms0_name} alarm PLCModuleAnomaly"
    alarm_mostempsensorabsent:
      name: "${bms0_name} alarm MOSTempSensorAbsent"
    alarm_battempsensor1absent:
      name: "${bms0_name} alarm BATTempSensor1Absent"
    alarm_battempsensor2absent:
      name: "${bms0_name} alarm BATTempSensor2Absent"
    alarm_battempsensor3absent:
      name: "${bms0_name} alarm BATTempSensor3Absent"
    alarm_battempsensor4absent:
      name: "${bms0_name} alarm BATTempSensor4Absent"
    alarm_battempsensor5absent:
      name: "${bms0_name} alarm BATTempSensor5Absent"

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    status_balancing:
      name: "${bms1_name} status balancing"
    status_precharging:
      name: "${bms1_name} status precharging"      
    status_charging:
      name: "${bms1_name} status charging"
    status_discharging:
      name: "${bms1_name} status discharging"
    status_online:
      name: "${bms1_name} status online"
    status_heating:
      name: "${bms1_name} status heating"      
    alarm_wireres:
      name: "${bms1_name} alarm WireRes"
    alarm_mosotp:
      name: "${bms1_name} alarm MosOTP"
    alarm_cellquantity:
      name: "${bms1_name} alarm CellQuantity"
    alarm_cursensorerr:
      name: "${bms1_name} alarm CurSensorErr"
    alarm_cellovp:
      name: "${bms1_name} alarm CellOVP"
    alarm_batovp:
      name: "${bms1_name} alarm BatOVP"
    alarm_chocp:
      name: "${bms1_name} alarm ChOCP"
    alarm_chscp:
      name: "${bms1_name} alarm ChSCP"
    alarm_chotp:
      name: "${bms1_name} alarm ChOTP"
    alarm_chutp:
      name: "${bms1_name} alarm ChUTP"
    alarm_cpuauxcommuerr:
      name: "${bms1_name} alarm CPUAuxCommuErr"
    alarm_celluvp:
      name: "${bms1_name} alarm CellUVP"
    alarm_batuvp:
      name: "${bms1_name} alarm BatUVP"
    alarm_dchocp:
      name: "${bms1_name} alarm DchOCP"
    alarm_dchscp:
      name: "${bms1_name} alarm DchSCP"
    alarm_dchotp:
      name: "${bms1_name} alarm DchOTP"
    alarm_chargemos:
      name: "${bms1_name} alarm ChargeMOS"
    alarm_dischargemos:
      name: "${bms1_name} alarm DischargeMOS"
    alarm_gpsdisconneted:
      name: "${bms1_name} alarm GPSDisconneted"
    alarm_modifypwdintime:
      name: "${bms1_name} alarm ModifyPWDinTime"
    alarm_dischargeonfailed:
      name: "${bms1_name} alarm DischargeOnFailed"
    alarm_batteryovertemp:
      name: "${bms1_name} alarm BatteryOverTemp"
    alarm_temperaturesensoranomaly:
      name: "${bms1_name} alarm TemperatureSensorAnomaly"
    alarm_plcmoduleanomaly:
      name: "${bms1_name} alarm PLCModuleAnomaly"
    alarm_mostempsensorabsent:
      name: "${bms1_name} alarm MOSTempSensorAbsent"
    alarm_battempsensor1absent:
      name: "${bms1_name} alarm BATTempSensor1Absent"
    alarm_battempsensor2absent:
      name: "${bms1_name} alarm BATTempSensor2Absent"
    alarm_battempsensor3absent:
      name: "${bms1_name} alarm BATTempSensor3Absent"
    alarm_battempsensor4absent:
      name: "${bms1_name} alarm BATTempSensor4Absent"
    alarm_battempsensor5absent:
      name: "${bms1_name} alarm BATTempSensor5Absent"

sensor:
  - platform: uptime
    id: uptime_sec
  # +--------------------------------------+
  # | Uptime sensor                        |
  # +--------------------------------------+
  - platform: uptime
    name: ${esp_name} Uptime Sensor
    id: uptime_sensor
    update_interval: 5s
    entity_category: diagnostic
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              char buf[10];
              int uptime_sec = round(id(uptime_sensor).raw_state);
              int days = (int)(uptime_sec / 86400);
              int hours = (int)((uptime_sec % 86400) / 3600);
              int minutes = (int)((uptime_sec % 3600) / 60);
              int seconds = (int)(uptime_sec % 60);

              return(
                (
                  (days ? sprintf(buf, "%02dd ", days), std::string(buf) : "") +
                  (hours ? sprintf(buf, "%02dh ", hours), std::string(buf) : "") +
                  (minutes ? sprintf(buf, "%02dm ", minutes), std::string(buf) : "") +
                  (sprintf(buf, "%02ds", seconds), std::string(buf))
                ).c_str()
              ); 

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing_direction:
      name: "${bms0_name} balancing direction"
    cell_voltage_min:
      name: "${bms0_name} cell voltage min"
    cell_voltage_max:
      name: "${bms0_name} cell voltage max"
    cell_voltage_min_cell_number:
      name: "${bms0_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      name: "${bms0_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${bms0_name} cell delta voltage"
    cell_average_voltage:
      name: "${bms0_name} cell average voltage"
    cell_resistance_min:
      name: "${bms0_name} cell resistance min"
    cell_resistance_max:
      name: "${bms0_name} cell resistance max"      
    cell_resistance_min_cell_number:
      name: "${bms0_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${bms0_name} cell resistance max cell number"      
    cell_voltage_01:
      name: "${bms0_name} cell voltage 01"
    cell_voltage_02:
      name: "${bms0_name} cell voltage 02"
    cell_voltage_03:
      name: "${bms0_name} cell voltage 03"
    cell_voltage_04:
      name: "${bms0_name} cell voltage 04"
    cell_voltage_05:
      name: "${bms0_name} cell voltage 05"
    cell_voltage_06:
      name: "${bms0_name} cell voltage 06"
    cell_voltage_07:
      name: "${bms0_name} cell voltage 07"
    cell_voltage_08:
      name: "${bms0_name} cell voltage 08"
    cell_voltage_09:
      name: "${bms0_name} cell voltage 09"
    cell_voltage_10:
      name: "${bms0_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms0_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms0_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms0_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms0_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms0_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms0_name} cell voltage 16"
    cell_resistance_01:
      name: "${bms0_name} cell resistance 01"
    cell_resistance_02:
      name: "${bms0_name} cell resistance 02"
    cell_resistance_03:
      name: "${bms0_name} cell resistance 03"
    cell_resistance_04:
      name: "${bms0_name} cell resistance 04"
    cell_resistance_05:
      name: "${bms0_name} cell resistance 05"
    cell_resistance_06:
      name: "${bms0_name} cell resistance 06"
    cell_resistance_07:
      name: "${bms0_name} cell resistance 07"
    cell_resistance_08:
      name: "${bms0_name} cell resistance 08"
    cell_resistance_09:
      name: "${bms0_name} cell resistance 09"
    cell_resistance_10:
      name: "${bms0_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms0_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms0_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms0_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms0_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms0_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms0_name} cell resistance 16"
    battery_voltage:
      name: "${bms0_name} battery voltage"
    battery_current:
      name: "${bms0_name} battery current"
    battery_power:
      name: "${bms0_name} battery power"
    battery_power_charging:
      name: "${bms0_name} battery power charging"
    battery_power_discharging:
      name: "${bms0_name} battery power discharging"
    temperature_sensor_1:
      name: "${bms0_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms0_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms0_name} temperature sensor 4"
    temperature_sensor_5:
      name: "${bms0_name} temperature sensor 5"
    temperature_powertube:
      name: "${bms0_name} temperature powertube"
    battery_capacity_state_of_charge:
      name: "${bms0_name} battery capacity state of charge"
    battery_capacity_remaining:
      name: "${bms0_name} battery capacity remaining"
    charging_cycles:
      name: "${bms0_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${bms0_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${bms0_name} battery total runtime"
    balancing_current:
      name: "${bms0_name} balancing current"
    errors_bitmask:
      name: "${bms0_name} errors bitmask"
    cell_count_real:
      name: "${bms0_name} cell count real"                                                       
    smart_sleep_time:
      name: "${bms0_name} smart sleep time"                              
    powertube_temperature_protection:
      name: "${bms0_name} powertube temperature protection" 
    powertube_temperature_protection_recovery:
      name: "${bms0_name} powertube temperature protection recovery"  
    battery_total_alarms_count:     
      name: "${bms0_name} battery total alarms count"  
    battery_total_alarms_active:     
      name: "${bms0_name} battery total alarms active"  
    emergency_time_countdown:
      name: "${bms0_name} emergency time countdown"      
    uart1_protocol_number:
      name: "${bms0_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${bms0_name} uart2 protocol number"  
    battery_soh_valuation:    
      name: "${bms0_name} battery soh valuation"
    discharging_overcurrent_protection_release_time:    
      name: "${bms0_name} discharging overcurrent protection release time"
    discharging_short_circuit_protection_release_time:    
      name: "${bms0_name} discharging short circuit protection release time"
    charging_overcurrent_protection_release_time:    
      name: "${bms0_name} charging overcurrent protection release time"
    charging_short_circuit_protection_release_time:    
      name: "${bms0_name} charging short circuit protection release time"
    cell_undervoltage_protection_release_time:    
      name: "${bms0_name} cell undervoltage protection release time"
    cell_overvoltage_protection_release_time:    
      name: "${bms0_name} cell overvoltage protection release time"


  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    balancing_direction:
      name: "${bms1_name} balancing direction"
    cell_voltage_min:
      name: "${bms1_name} cell voltage min"
    cell_voltage_max:
      name: "${bms1_name} cell voltage max"
    cell_voltage_min_cell_number:
      name: "${bms1_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      name: "${bms1_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${bms1_name} cell delta voltage"
    cell_average_voltage:
      name: "${bms1_name} cell average voltage"
    cell_resistance_min:
      name: "${bms1_name} cell resistance min"
    cell_resistance_max:
      name: "${bms1_name} cell resistance max"      
    cell_resistance_min_cell_number:
      name: "${bms1_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${bms1_name} cell resistance max cell number"        
    cell_voltage_01:
      name: "${bms1_name} cell voltage 01"
    cell_voltage_02:
      name: "${bms1_name} cell voltage 02"
    cell_voltage_03:
      name: "${bms1_name} cell voltage 03"
    cell_voltage_04:
      name: "${bms1_name} cell voltage 04"
    cell_voltage_05:
      name: "${bms1_name} cell voltage 05"
    cell_voltage_06:
      name: "${bms1_name} cell voltage 06"
    cell_voltage_07:
      name: "${bms1_name} cell voltage 07"
    cell_voltage_08:
      name: "${bms1_name} cell voltage 08"
    cell_voltage_09:
      name: "${bms1_name} cell voltage 09"
    cell_voltage_10:
      name: "${bms1_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms1_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms1_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms1_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms1_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms1_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms1_name} cell voltage 16"
    cell_resistance_01:
      name: "${bms1_name} cell resistance 01"
    cell_resistance_02:
      name: "${bms1_name} cell resistance 02"
    cell_resistance_03:
      name: "${bms1_name} cell resistance 03"
    cell_resistance_04:
      name: "${bms1_name} cell resistance 04"
    cell_resistance_05:
      name: "${bms1_name} cell resistance 05"
    cell_resistance_06:
      name: "${bms1_name} cell resistance 06"
    cell_resistance_07:
      name: "${bms1_name} cell resistance 07"
    cell_resistance_08:
      name: "${bms1_name} cell resistance 08"
    cell_resistance_09:
      name: "${bms1_name} cell resistance 09"
    cell_resistance_10:
      name: "${bms1_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms1_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms1_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms1_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms1_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms1_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms1_name} cell resistance 16"
    battery_voltage:
      name: "${bms1_name} battery voltage"
    battery_current:
      name: "${bms1_name} battery current"
    battery_power:
      name: "${bms1_name} battery power"
    battery_power_charging:
      name: "${bms1_name} battery power charging"
    battery_power_discharging:
      name: "${bms1_name} battery power discharging"
    temperature_sensor_1:
      name: "${bms1_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms1_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms1_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms1_name} temperature sensor 4"
    temperature_sensor_5:
      name: "${bms1_name} temperature sensor 5"      
    temperature_powertube:
      name: "${bms1_name} temperature powertube"
    battery_capacity_state_of_charge:
      name: "${bms1_name} battery capacity state of charge"
    battery_capacity_remaining:
      name: "${bms1_name} battery capacity remaining"
    charging_cycles:
      name: "${bms1_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${bms1_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${bms1_name} battery total runtime"
    balancing_current:
      name: "${bms1_name} balancing current"
    errors_bitmask:
      name: "${bms1_name} errors bitmask"
    cell_count_real:
      name: "${bms1_name} cell count real"                                     
    smart_sleep_time:
      name: "${bms1_name} smart sleep time"                              
    powertube_temperature_protection:
      name: "${bms1_name} powertube temperature protection" 
    powertube_temperature_protection_recovery:
      name: "${bms1_name} powertube temperature protection recovery"  
    battery_total_alarms_count:     
      name: "${bms1_name} battery total alarms count"  
    battery_total_alarms_active:     
      name: "${bms1_name} battery total alarms active"           
    emergency_time_countdown:
      name: "${bms1_name} emergency time countdown"
    uart1_protocol_number:
      name: "${bms1_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${bms1_name} uart2 protocol number"
    battery_soh_valuation:    
      name: "${bms1_name} battery soh valuation"
    discharging_overcurrent_protection_release_time:    
      name: "${bms1_name} discharging overcurrent protection release time"
    discharging_short_circuit_protection_release_time:    
      name: "${bms1_name} discharging short circuit protection release time"
    charging_overcurrent_protection_release_time:    
      name: "${bms1_name} charging overcurrent protection release time"
    charging_short_circuit_protection_release_time:    
      name: "${bms1_name} charging short circuit protection release time"
    cell_undervoltage_protection_release_time:    
      name: "${bms1_name} cell undervoltage protection release time"
    cell_overvoltage_protection_release_time:    
      name: "${bms1_name} cell overvoltage protection release time"

switch:
  - platform: template
    name: "Broadcast changes to all BMSs"
    id: broadcast_active
    icon: "mdi:cast"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(sniffer0).set_broadcast_changes_to_all_bms(true);  
    turn_off_action:
      - lambda: |-
          id(sniffer0).set_broadcast_changes_to_all_bms(false);          

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    precharging:
      name: "${bms0_name} precharging"
    charging:
      name: "${bms0_name} charging"
    discharging:
      name: "${bms0_name} discharging"
    balancing:
      name: "${bms0_name} balancing"
    emergency:
      name: "${bms0_name} emergency"
    heating:
      name: "${bms0_name} heating"
    display_always_on:
      name: "${bms0_name} display_always_on"
    charging_float_mode:
      name: "${bms0_name} charging float mode"
    timed_stored_data:
      name: "${bms0_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms0_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms0_name} smart sleep on"
    disable_pcl_module:
      name: "${bms0_name} disable pcl module"
    gps_heartbeat:
      name: "${bms0_name} gps heartbeat"
    port_selection:
      name: "${bms0_name} port selection"
    special_charger:
      name: "${bms0_name} special charger"            


  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    precharging:
      name: "${bms1_name} precharging"
    charging:
      name: "${bms1_name} charging"
    discharging:
      name: "${bms1_name} discharging"
    balancing:
      name: "${bms1_name} balancing"
    emergency:
      name: "${bms1_name} emergency"
    heating:
      name: "${bms1_name} heating"
    display_always_on:
      name: "${bms1_name} display_always_on"
    charging_float_mode:
      name: "${bms1_name} charging float mode"
    timed_stored_data:
      name: "${bms1_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms1_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms1_name} smart sleep on"
    disable_pcl_module:
      name: "${bms1_name} disable pcl module"
    gps_heartbeat:
      name: "${bms1_name} gps heartbeat"
    port_selection:
      name: "${bms1_name} port selection"
    special_charger:
      name: "${bms1_name} special charger" 
      

text_sensor:
  # +--------------------------------------+
  # | Uptime Human Readable                |
  # +--------------------------------------+
  - platform: template
    name: ${esp_name} Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    errors:
      name: "${bms0_name} errors"
    operation_status:
      name: "${bms0_name} operation status"
    battery_type:
      name: "${bms0_name} battery type"
    total_runtime_formatted:
      name: "${bms0_name} total runtime formatted"
    info_vendorid:
      name: "${bms0_name} info vendorid"
    info_hardware_version:
      name: "${bms0_name} info hardware version"
    info_software_version:
      name: "${bms0_name} info software version"
    info_device_name:
      name: "${bms0_name} info device name"
    info_device_password:
      name: "${bms0_name} info device password"   
    network_nodes_available:
      name: "${bms0_name} network nodes available"  
    info_device_serial_number:
      name: "${bms0_name} info device serial number"  
    info_device_setup_passcode:
      name: "${bms0_name} info device setup passcode"   

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    errors:
      name: "${bms1_name} errors"
    operation_status:
      name: "${bms1_name} operation status"
    battery_type:
      name: "${bms1_name} battery type"
    total_runtime_formatted:
      name: "${bms1_name} total runtime formatted"
    info_vendorid:
      name: "${bms1_name} info vendorid"
    info_hardware_version:
      name: "${bms1_name} info hardware version"
    info_software_version:
      name: "${bms1_name} info software version"
    info_device_name:
      name: "${bms1_name} info device name"
    info_device_password:
      name: "${bms1_name} info device password"   
    network_nodes_available:
      name: "${bms1_name} network nodes available"  
    info_device_serial_number:
      name: "${bms1_name} info device serial number"  
    info_device_setup_passcode:
      name: "${bms1_name} info device setup passcode"  

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0 
    cell_smart_sleep_voltage:
      name: "${bms0_name} cell smart sleep voltage"  
    cell_undervoltage_protection:
      name: "${bms0_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms0_name} cell undervoltage protection recovery" 
    cell_overvoltage_protection:
      name: "${bms0_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms0_name} cell overvoltage protection recovery"
    cell_balancing_trigger_voltage:
      name: "${bms0_name} cell balancing trigger voltage" 
    cell_soc100_voltage:
      name: "${bms0_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms0_name} cell soc0 voltage"    
    cell_request_charge_voltage:
      name: "${bms0_name} cell request charge voltage"          
    cell_request_float_voltage:
      name: "${bms0_name} cell request float voltage"   
    cell_power_off_voltage:
      name: "${bms0_name} cell power off voltage"  
    cell_balancing_starting_voltage:
      name: "${bms0_name} cell balancing starting voltage"        
    max_charging_current:
      name: "${bms0_name} max charging current"          
    charging_overcurrent_protection_delay:
      name: "${bms0_name} charging overcurrent protection delay"
    charging_overcurrent_protection_recovery_delay:
      name: "${bms0_name} charging overcurrent protection recovery delay"
    max_discharging_current:
      name: "${bms0_name} max discharging current"     
    discharging_overcurrent_protection_delay:
      name: "${bms0_name} discharging overcurrent protection delay"
    discharging_overcurrent_protection_recovery_delay:
      name: "${bms0_name} discharging overcurrent protection recovery delay"
    short_circuit_protection_delay:
      name: "${bms0_name} short circuit protection delay"        
    short_circuit_protection_recovery_delay:
      name: "${bms0_name} short circuit protection recovery delay" 
    max_balancing_current:
      name: "${bms0_name} max balancing current" 
    charging_overtemperature_protection:
      name: "${bms0_name} charging overtemperature protection"
    charging_overtemperature_protection_recovery:
      name: "${bms0_name} charging overtemperature protection recovery"
    discharging_overtemperature_protection:
      name: "${bms0_name} discharging overtemperature protection"
    discharging_overtemperature_protection_recovery:
      name: "${bms0_name} discharging overtemperature protection recovery" 
    charging_lowtemperature_protection:
      name: "${bms0_name} charging lowtemperature protection"
    charging_lowtemperature_protection_recovery:
      name: "${bms0_name} charging lowtemperature protection recovery"
    mos_overtemperature_protection:
      name: "${bms0_name} mos overtemperature protection"
    mos_overtemperature_protection_recovery:
      name: "${bms0_name} mos overtemperature protection recovery"   
    cell_count_settings:
      name: "${bms0_name} cell count settings"      
    battery_capacity_total_settings:
      name: "${bms0_name} battery capacity total settings"            
    precharging_time_from_discharge:
      name: "${bms0_name} precharging time from discharge"
    cell_request_charge_voltage_time:
      name: "${bms0_name} cell request charge voltage time" 
    cell_request_float_voltage_time:
      name: "${bms0_name} cell request float voltage time"       
      
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1 
    cell_smart_sleep_voltage:
      name: "${bms1_name} cell smart sleep voltage"  
    cell_undervoltage_protection:
      name: "${bms1_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms1_name} cell undervoltage protection recovery"   
    cell_overvoltage_protection:
      name: "${bms1_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms1_name} cell overvoltage protection recovery"      
    cell_balancing_trigger_voltage:
      name: "${bms1_name} cell balancing trigger voltage"   
    cell_soc100_voltage:
      name: "${bms1_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms1_name} cell soc0 voltage" 
    cell_request_charge_voltage:
      name: "${bms1_name} cell request charge voltage"          
    cell_request_float_voltage:
      name: "${bms1_name} cell request float voltage"   
    cell_power_off_voltage:
      name: "${bms1_name} cell power off voltage" 
    cell_balancing_starting_voltage:
      name: "${bms1_name} cell balancing starting voltage"        
    max_charging_current:
      name: "${bms1_name} max charging current"     
    charging_overcurrent_protection_delay:
      name: "${bms1_name} charging overcurrent protection delay"
    charging_overcurrent_protection_recovery_delay:
      name: "${bms1_name} charging overcurrent protection recovery delay"         
    max_discharging_current:
      name: "${bms1_name} max discharging current"     
    discharging_overcurrent_protection_delay:
      name: "${bms1_name} discharging overcurrent protection delay"
    discharging_overcurrent_protection_recovery_delay:
      name: "${bms1_name} discharging overcurrent protection recovery delay"
    short_circuit_protection_delay:
      name: "${bms1_name} short circuit protection delay"  
    short_circuit_protection_recovery_delay:
      name: "${bms1_name} short circuit protection recovery delay"   
    max_balancing_current:
      name: "${bms1_name} max balancing current"      
    charging_overtemperature_protection:
      name: "${bms1_name} charging overtemperature protection"
    charging_overtemperature_protection_recovery:
      name: "${bms1_name} charging overtemperature protection recovery"
    discharging_overtemperature_protection:
      name: "${bms1_name} discharging overtemperature protection"
    discharging_overtemperature_protection_recovery:
      name: "${bms1_name} discharging overtemperature protection recovery"        
    charging_lowtemperature_protection:
      name: "${bms1_name} charging lowtemperature protection"
    charging_lowtemperature_protection_recovery:
      name: "${bms1_name} charging lowtemperature protection recovery"
    mos_overtemperature_protection:
      name: "${bms1_name} mos overtemperature protection"
    mos_overtemperature_protection_recovery:
      name: "${bms1_name} mos overtemperature protection recovery"      
    cell_count_settings:
      name: "${bms1_name} cell count settings"
    battery_capacity_total_settings:
      name: "${bms1_name} battery capacity total settings"      
    precharging_time_from_discharge:
      name: "${bms1_name} precharging time from discharge"  
    cell_request_charge_voltage_time:
      name: "${bms1_name} cell request charge voltage time"       
    cell_request_float_voltage_time:
      name: "${bms1_name} cell request float voltage time"       
```

Probably an error on my side but I can not figure it out. I have also tried versions `2.0.1` and `2.2`.

[logs_jkmonitor_logs.txt](https://github.com/user-attachments/files/19052367/logs_jkmonitor_logs.txt)
