### ISSUE TITLE
RS485 one master & one slave configuration, slave is missing

### ISSUE THREAD

**Issue by LithiumNL** [txubelaxu/esphome-jk-bms#55]
When using this repo i can't get any data from the slave device in master & slave configuration.
Configured the master at address 0 and the slave at address 1. Everything is fine with the JK desktop app.

- When using only one device as master i have no issues getting data, everything is fine.
- When using only one slave at address everything is fine as well. I used the slave that i used as slave with the master combination so there is data coming from the slave.
- When using both I only get data from the master.

BMS boards are hardware V15 and software V15.41.
It feels like when using master & slave the slave does not been polled.
The logs show this: 
```
This BMS address is: 1  and address received 0 ==> 'IDLE'  
```

Hope someone has the same experience and we can fix this.
Below my configuration (left out the sensors etc)(used the ˋesp32-example-jkpb-rs485_1master_1slave.yamlˋ as an example)

```
substitutions:
  esp_name: esp-rs485-jk-bms
  bms0_name: master-bms
  bms1_name: slave-bms
  device_description: "Monitor two JK-BMS via RS485 internal"
  external_components_source: github://rabbit3dcustom/esphome-jk-bms@main #github://rabbit3dcustom/esphome-jk-bms@main #github://brycelarge/esphome-jk-bms@main #github://txubelaxu/esphome-jk-bms@main #github://syssi/esphome-jk-bms@main
  tx_pin_uart_0: GPIO1 #GPIO17 GPIO1 #GPIO16
  rx_pin_uart_0: GPIO3 #GPIO16 GPIO3 #GPIO17
  talk_pin_rs485: GPIO17
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: "JK02_32S"

esphome:
  name: ${esp_name}
  comment: ${device_description}
  project:
    name: "rabbit3dcustom.esphome-jk-bms"
    version: 2.0.1

esp32:
  #board: esp32dev
  board: wemos_d1_mini32

external_components:
  - source: ${external_components_source}
    refresh: 0s
    #components: [ json, jk_rs485_sniffer , jk_rs485_bms ]

logger:
  level: DEBUG #VERBOSE #DEBUG #INFO #VERY_VERBOSE #VERBOSE #DEBUG #INFO #DEBUG
  tx_buffer_size: 2048

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: xxx
  password: xxx
  manual_ip: 
    static_ip: xxx
    gateway: xxx
    subnet: xxx

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 500
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: "JK02_32S"
    rx_timeout: 500ms
    uart_id: uart_0
    talk_pin: ${talk_pin_rs485}

jk_rs485_bms:
  - id: bms1
    rs485_address: 0x01
    jk_rs485_sniffer_id: sniffer0
    update_interval: 30s
  - id: bms0
    rs485_address: 0x00
    jk_rs485_sniffer_id: sniffer0
    update_interval: 30s
```

@txubelaxu would you please mind to help us out?
